### ISSUE TITLE
flutter-glow is about to be incompataible with Flutter

### ISSUE THREAD

**Issue by gslender** [payam-zahedi/flutter-glow#6]
Current beta channel is not compatiable and is about to be made stable, so without changes this package will stop working.

`Error (Xcode): ../../.pub-cache/hosted/pub.dev/flutter_glow-0.2.0/lib/src/widget/glow_line_progress.dart:34:61: Error: The getter 'accentColor' isn't defined for the class 'ThemeData'.`

**Comment by payam-zahedi** [comment]
Thanks for this issue
I'll try to migrate it with new flutter version

**Comment by payam-zahedi** [comment]
Hey @gslender 
the new version of the flutter glow is out
https://pub.dev/packages/flutter_glow

I'll close this issue for now, if you have any question please let me know
